### ISSUE TITLE
Pypi package fails installing on Python 3.9.2

### ISSUE THREAD

**Issue by sisoma2** [drstrng/pype32-py3#1]
Hi,

I've tried to install pype32-py3 with the command `pip install pype32-py3` and I get an error.
The python version that I'm currently running is Python 3.9.2.

![imagen](https://user-images.githubusercontent.com/7660940/109139683-151f4700-775c-11eb-9758-aa9b1ec34af0.png)

**Comment by drstrng** [comment]
ok, error reproduced

**Comment by drstrng** [comment]
a new release v0.2 resolves this issue for python 3.9.2.  please try installing again!  thank you for reporting the issue.
pip install pype32-py3
